global:
  scrape_interval: 10s
scrape_configs:
  - job_name: Prometheus Server
    static_configs:
{% for host in groups['prometheus-server'] %}
      - targets: ['{{ host }}:9090']
{% endfor %}
  - job_name: Node Exporters
    static_configs:
      - targets:
{% for host in groups['exporters'] %}
          - {{ host }}
{% endfor %}
